### ISSUE TITLE
group1 empty on perfect regex match  

### ISSUE THREAD

**Issue by Tchekda** [actions-ecosystem/action-regex-match#158]
## What happened
When running this action : 
```yml
      - name: Extract version number
        id: version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '.*(v\d+\.\d+\.\d+).*'
      - name: Create Release
        if: ${{ steps.version.outputs.match != '' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.version.outputs.group1 }}
          title: Version ${{ steps.version.outputs.group1 }}
```

With the commit message `v0.0.8`, the second step is triggered so `steps.version.outputs.match` isn't empty but `steps.version.outputs.group1` is empty that creates an error on the following step. But when the commit message is `v0.0.8 - 2nd try` it's working fine and the `steps.version.outputs.group1` contains correctly the version number.

[Regex101 proof](https://regex101.com/r/NMwO04/1)

## What you expected to happen

I expected the regex to match the whole message as expected and put it in `steps.version.outputs.group1`

## How to reproduce it

Use these steps on an action triggered by push and create a commit matching perfectly the regex

## Environment

These action are set with `runs-on: ubuntu-latest`
