### ISSUE TITLE
problem for multiple matches

### ISSUE THREAD

**Issue by LouisCoilliot** [actions-ecosystem/action-regex-match#230]
## What happened

Using :

```
      - uses: actions-ecosystem/action-regex-match@v2.0.2
        id: regex-match
        with:
          text: "${{ steps.changed-files.outputs.all_modified_files }}"
          regex: 'inventory\/(.*?)\/'
          # all matches, not just first one
          flags: gm
      - name: debug steps.regex-match.outputs
        run: echo "$DBG"
        env:
          DBG: ${{ toJson(steps.regex-match.outputs) }}

```

The search being (from the job logs):

```
Run actions-ecosystem/action-regex-match@v2.0.2
  with:
    text: inventory/usglb-dev1/inventory.ini,inventory/usglb-dev2/inventory.ini
    regex: inventory\/(.*?)\/
    flags: gm
```

## What you expected to happen

It should match 'usglb-dev1' AND 'usglb-dev2'

It only matches : 

```
Run echo "$DBG"
{
  "match": "inventory/usglb-dev1/",
  "group1": "usglb-dev1"
}
```

I checked the regex, see image in attachment.

![regex-test](https://user-images.githubusercontent.com/85882366/135487060-27620779-e42a-4e0e-94c2-c8ab382f97a7.png)

Regards,

Louis

Louis
