### ISSUE TITLE
tags doesn't match

### ISSUE THREAD

**Issue by PPCM** [actions-ecosystem/action-regex-match#256]
The behaviour with tags is strange.

For example:

With the following code
```
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Version match
        uses: actions-ecosystem/action-regex-match@v2
        id: version-match
        with:
          text: ${GITHUB_REF#refs/tags/}
          regex: '^(.*)'
```
With the tag '1.2.3', it matches '1.2.3'

But with the following code
```
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Version match
        uses: actions-ecosystem/action-regex-match@v2
        id: version-match
        with:
          text: ${GITHUB_REF#refs/tags/}
          regex: '^([0-9]*)'
```
Still with a same tag, it matches ''

And finally with the following code
```
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Version match
        uses: actions-ecosystem/action-regex-match@v2
        id: version-match
        with:
          text: '1.2.3'
          regex: '^([0-9]*)'
```
It matches '1'

Any idea why?
