### ISSUE TITLE
Simply doesn't work

### ISSUE THREAD

**Issue by lukepighetti** [actions-ecosystem/action-regex-match#289]
Hello, I tried to use this to extract `1.0.0` from `refs/heads/release/1.0.0`, but failed.

```yaml
jobs:
  deploy:
    name: Deploy to TestFlight
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: branch-version-regex
        with:
          text: "${{ github.ref }}"
          regex: '\d+\.\d+\.\d+$'

      - run: echo '${{ github.ref }}'
      - run: echo '${{ steps.branch-version-regex.outputs.group1 }}'
```

This outputs

- `echo 'refs/heads/release/1.0.0'`
- `echo ''`

**Comment by HelloRusk** [comment]
seems duplicated to https://github.com/actions-ecosystem/action-regex-match/issues/158
use `.+?` instead of `\d+`

**Comment by AyushiBShah** [comment]
/<a [^>]*\bhref\s*=\s*"([^"]*vercel.app[^"]*)/

This is not working for me @kaisugi @lukepighetti

**Comment by lukepighetti** [comment]
> seems duplicated to #158
> use `.+?` instead of `\d+`

`.` and `\d` are not the same delimiters

**Comment by jtmuller5** [comment]
It seems like the issue is that `group1` can be empty while `match` contains a value. I used this code to extract the version name from a git tag (v1.5.5+157):

```
- name: 'Extract version name from tag'
        uses: actions-ecosystem/action-regex-match@v2
        id: version-name
        with:
          text: ${{ env.VERSION_NAME }}
          regex: '[0-9]+\.[0-9]+\.[0-9]+' # https://regexr.com/
```
When I printed out the results, `group1` is blank and `match` contained the correct value (1.5.5):

```
 - name: 'Print extracted values'
        run: |
          echo ${{ steps.version-name.outputs.group1 }} // ''
          echo ${{ steps.version-name.outputs.match }} // '1.5.5'
```
